services:
  postgres:
    image: postgres:15-alpine
    container_name: cinema-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - cinema-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 1. DISCOVERY SERVER - DÉMARRE EN PREMIER
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server-test
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cinema-network

  # 2. MOVIE SERVICE (déjà testé et fonctionnel)
  movie-service:
    build: ./service-film
    container_name: movie-service-test
    ports:
      - "7080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - discovery-server
    networks:
      - cinema-network

  # 3. USER MANAGEMENT
  user-management:
    build: ./user-management
    container_name: user-management-test
    ports:
      - "7082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - discovery-server
    networks:
      - cinema-network

  # 4. BOOKING SERVICE
  booking-service:
    build: ./service-reservation
    container_name: booking-service-test
    ports:
      - "7083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - discovery-server
      - user-management
    networks:
      - cinema-network

  # 5. CINEMA SERVICE
  cinema-service:
    build: ./cinema
    container_name: cinema-service-test
    ports:
      - "7081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - discovery-server
      - booking-service
    networks:
      - cinema-network

volumes:
  postgres_data:

networks:
  cinema-network:
    driver: bridge