server:
  port: 8888  # Port du config-server

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/errmili/config-repo.git  # Ton repo est correct
          default-label: main
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
